#!/bin/bash

set -e

echo '-------> Source code retrieval starting'
SOURCE_TARGET="$1"
if [ -z "$SOURCE_TARGET" ]; then
    echo "No argument found, first argument to run this container should be the http (and later s3/local file) location of the source package"
    exit 1
fi
cd /tmp/buildpack-cache
wget -O source.zip "$SOURCE_TARGET"
unzip -qo source.zip -d /home/vcap

DIGEST=$(sha256sum source.zip | cut -d ' ' -f 1)
echo '-------> Source code retrieved ' $DIGEST

if [ -f "${DIGEST}.zip" ]; then
    echo '-------> Cached droplet detected, starting that'
    unzip -qo /tmp/buildpack-cache/${DIGEST}.zip -d /home/vcap
else
    echo '-------> Buildpack detection starting'
    MATCH=''
    for buildpack in $(ls -1 /srv/buildpacks); do
        if /srv/buildpacks/$buildpack/bin/detect /home/vcap/ 1>/dev/null; then
            echo $buildpack matches
            MATCH="$buildpack"
        fi
    done

    if [ -z "$MATCH" ]; then
        echo "No matching buildpack found"
        exit 1
    fi


    export CF_STACK=cflinuxfs2


    echo '-------> Buildpack compile starting'
    mkdir -p /tmp/buildpack-cache
    cd /home/vcap
    /srv/buildpacks/$MATCH/bin/compile /home/vcap /tmp/buildpack-cache


    echo '-------> Creating droplet for cache'
    cd /home/vcap
    zip -qr /tmp/buildpack-cache/${DIGEST}.zip .
fi


echo '-------> Buildpack completed, starting app'

if [ -x /srv/buildpacks/$MATCH/bin/release ]; then
    set +e
    X=$(/srv/buildpacks/$MATCH/bin/release /home/vcap | python -c "import yaml, sys; print(yaml.load(sys.stdin)['default_process_types']['web'])")
    set -e
    if [ -n "$X" ]; then
        CMD="$X"
    fi
fi

if [ -f /home/vcap/Procfile ]; then
    set +e
    X=$(cat /home/vcap/Procfile | python -c "import yaml, sys; print(yaml.load(sys.stdin)['web'])")
    set -e
    if [ -n "$X" ]; then
        CMD="$X"
    fi
fi

chown -R vcap:vcap /home/vcap
rm -rf /app
ln -sfT /home/vcap /app
cd /home/vcap

export VCAP_APP_PORT=8080
export PORT=$VCAP_APP_PORT

mkdir -p /home/vcap/.profile.d
touch /home/vcap/.profile.d/no-glob-errors

cat /home/vcap/.profile.d/* > /tmp/profile
rm -rf /home/vcap/.profile.d
mkdir -p /home/vcap/.profile.d
mv /tmp/profile /home/vcap/.profile.d/concatenated

sudo --preserve-env --set-home -u vcap /bin/bash --login -c "source /home/vcap/.profile.d/concatenated; $CMD"
